/**
 * Faithful Workflows — Domain Types (JSDoc)
 *
 * All types are plain JS objects. These JSDoc definitions serve as the
 * authoritative shape contract for the recommendation engine and UI.
 */

/**
 * @typedef {'safety'|'clinical_caution'|'session_focus'|'homework'|'relationship'|'spiritual'|'coordination'|'monitoring'} RecommendationCategory
 */

/**
 * @typedef {'pending'|'complete'|'deferred'|'hidden'} RecommendationStatus
 */

/**
 * @typedef {'generate_session_agenda'|'generate_note_prep'|'suggest_verses'|'create_prayer_prompt'|'create_cbt_exercise'|'create_journal_prompt'|'draft_followup_message'|'add_reminder_task'|'create_treatment_plan_update'|'mark_complete'|'defer'|'hide'} ActionType
 */

/**
 * @typedef {'improving'|'stable'|'declining'|'unknown'} TrendDirection
 */

/**
 * @typedef {'critical'|'high'|'moderate'|'routine'} UrgencyLevel
 */

/**
 * A single care recommendation generated by a named rule.
 *
 * @typedef {Object} Recommendation
 * @property {string}                 id           — globally unique: `${ruleId}:${clientId}`
 * @property {string}                 ruleId       — name of the rule that fired (traceable)
 * @property {RecommendationCategory} category
 * @property {string}                 title
 * @property {string}                 summary      — 1–2 sentence display summary
 * @property {string}                 rationale    — full explanation with data values interpolated
 * @property {string[]}               evidence     — 1–4 data snippets that triggered the rule
 * @property {number}                 priority     — 1–10 integer (10 = most urgent)
 * @property {number}                 confidence   — 0.0–1.0 float
 * @property {string[]}               cautions     — optional clinical caution notes
 * @property {ActionType[]}           actions      — action buttons to show
 * @property {string|null}            faithNote    — optional faith-integrated note; never required
 * @property {RecommendationStatus}   status
 * @property {string|null}            orderedAfter — id of recommendation this should follow
 * @property {string}                 docNote      — documentation consideration note
 */

/**
 * Scored assessment record.
 *
 * @typedef {Object} AssessmentScore
 * @property {string}      id
 * @property {string}      inventoryName  — e.g. 'PHQ-9'
 * @property {number|null} score
 * @property {string|null} scoredAt       — ISO date string
 * @property {string|null} completedAt
 */

/**
 * Enriched data for a single client, loaded lazily when the client is selected.
 *
 * @typedef {Object} ClientWorkflowData
 * @property {Object}           client         — base client record
 * @property {Object[]}         diagnoses
 * @property {Object[]}         progressNotes
 * @property {Object|null}      treatmentPlan
 * @property {Object|null}      faithProfile
 * @property {Object[]}         appointments
 * @property {AssessmentScore[]} assessments   — scored form submissions
 * @property {'loading'|'ready'|'error'} status
 * @property {string|null}      errorMessage
 */

/**
 * A client row entry used to populate and rank the left-panel client list.
 *
 * @typedef {Object} ClientRankEntry
 * @property {string}        clientId
 * @property {string}        displayName
 * @property {string}        status         — client status (active, waitlist, etc.)
 * @property {boolean}       highTouchpoint
 * @property {number}        urgencyScore   — 0–100 composite score
 * @property {UrgencyLevel}  urgencyLevel
 * @property {number}        recommendationCount
 * @property {string[]}      topReasonChips — max 3 short reason labels
 * @property {string}        diagnosisSummary
 * @property {string|null}   lastActivityDate
 * @property {TrendDirection} trend
 * @property {Recommendation[]} recommendations
 */

export const CATEGORY_ORDER = [
  'safety',
  'clinical_caution',
  'session_focus',
  'homework',
  'relationship',
  'spiritual',
  'coordination',
  'monitoring',
];

export const CATEGORY_COLORS = {
  safety:           'red',
  clinical_caution: 'orange',
  session_focus:    'blue',
  homework:         'cyan',
  relationship:     'indigo',
  spiritual:        'grape',
  coordination:     'gray',
  monitoring:       'teal',
};

export const CATEGORY_ICONS = {
  safety:           '🚨',
  clinical_caution: '⚠️',
  session_focus:    '🎯',
  homework:         '📝',
  relationship:     '🤝',
  spiritual:        '✝️',
  coordination:     '📋',
  monitoring:       '📊',
};

/** Priority threshold above which a recommendation cannot be hidden or deferred. */
export const SAFETY_LOCK_THRESHOLD = 9;
