// Long Intake Form — comprehensive pre-counseling assessment (~30–45 minutes)
export const LongIntakeForm = {
  id: 'long_intake',
  title: 'Long Intake Form',
  description:
    'A comprehensive intake questionnaire used to gather detailed background information before beginning a counseling relationship. Takes approximately 30–45 minutes.',
  icon: '📄',
  color: 'brand',
  estimatedMinutes: 40,
  sections: [
    // ─── 1. Personal Information ────────────────────────────────────────────
    {
      id: 'personal',
      title: 'Personal Information',
      fields: [
        { id: 'firstName',   label: 'First Name',    type: 'text',  required: true,  half: true },
        { id: 'lastName',    label: 'Last Name',     type: 'text',  required: true,  half: true },
        { id: 'preferredName', label: 'Preferred Name / Nickname', type: 'text', half: true },
        { id: 'dob',         label: 'Date of Birth', type: 'date',  required: true,  half: true },
        { id: 'gender',      label: 'Gender Identity', type: 'select', half: true,
          options: ['Male', 'Female', 'Non-binary / Non-conforming', 'Transgender Male', 'Transgender Female', 'Prefer not to say', 'Other'] },
        { id: 'pronouns',    label: 'Preferred Pronouns', type: 'select', half: true,
          options: ['He / Him', 'She / Her', 'They / Them', 'Prefer not to say', 'Other'] },
        { id: 'race',        label: 'Race / Ethnicity', type: 'select', half: true,
          options: ['White / Caucasian', 'Black / African American', 'Hispanic / Latino', 'Asian / Pacific Islander',
            'Native American / Alaska Native', 'Multiracial', 'Middle Eastern / North African', 'Prefer not to say', 'Other'] },
        { id: 'ssn',         label: 'Last 4 of SSN (optional)', type: 'text', half: true, placeholder: 'XXXX' },
        { id: 'phone',       label: 'Primary Phone',  type: 'tel',   required: true,  half: true },
        { id: 'phoneType',   label: 'Phone Type',     type: 'select', half: true,
          options: ['Cell', 'Home', 'Work'] },
        { id: 'altPhone',    label: 'Alternate Phone', type: 'tel',  half: true },
        { id: 'email',       label: 'Email Address',  type: 'email', required: true,  half: true },
        { id: 'address',     label: 'Street Address', type: 'text',  required: true },
        { id: 'city',        label: 'City',           type: 'text',  required: true,  half: true },
        { id: 'state',       label: 'State',          type: 'text',  required: true,  half: true },
        { id: 'zip',         label: 'ZIP Code',       type: 'text',  required: true,  half: true },
        { id: 'country',     label: 'Country',        type: 'text',  half: true, placeholder: 'United States' },
        { id: 'maritalStatus', label: 'Marital Status', type: 'select', half: true,
          options: ['Single', 'Married', 'Separated', 'Divorced', 'Widowed', 'Partnered / Engaged', 'Cohabitating'] },
        { id: 'spouseName',  label: 'Spouse / Partner Name (if applicable)', type: 'text', half: true },
        { id: 'numberOfChildren', label: 'Number of Children', type: 'number', half: true, min: 0 },
        { id: 'childrenAges', label: 'Ages of Children', type: 'text', half: true, placeholder: 'e.g., 4, 9, 14' },
        { id: 'livingSituation', label: 'Current Living Situation', type: 'select',
          options: ['Own home', 'Renting alone', 'With spouse / partner', 'With family', 'With roommates', 'Assisted living', 'Homeless / unstable', 'Other'] },
        { id: 'occupation',  label: 'Occupation / Job Title', type: 'text',  half: true },
        { id: 'employer',    label: 'Employer / School',       type: 'text',  half: true },
        { id: 'referredBy',  label: 'How did you hear about us?', type: 'text' },
      ],
    },

    // ─── 2. Emergency Contact ────────────────────────────────────────────────
    {
      id: 'emergency',
      title: 'Emergency Contact',
      fields: [
        { id: 'ecName',         label: 'Emergency Contact Full Name', type: 'text', required: true, half: true },
        { id: 'ecRelationship', label: 'Relationship to You',         type: 'text', required: true, half: true },
        { id: 'ecPhone',        label: 'Emergency Contact Phone',     type: 'tel',  required: true, half: true },
        { id: 'ecAltPhone',     label: 'Alternate Phone',             type: 'tel',  half: true },
        { id: 'ecEmail',        label: 'Emergency Contact Email',     type: 'email', half: true },
        { id: 'ecAuthorized',   label: 'May we contact this person in a clinical emergency?', type: 'radio', options: ['Yes', 'No'] },
        { id: 'ecAdditional',   label: 'Additional authorized contacts (name and relationship)', type: 'textarea', minRows: 2 },
      ],
    },

    // ─── 3. Presenting Concerns ─────────────────────────────────────────────
    {
      id: 'presenting',
      title: 'Presenting Concerns',
      fields: [
        {
          id: 'primaryConcern',
          label: 'What is your primary reason for seeking counseling?',
          type: 'textarea',
          required: true,
          minRows: 4,
          placeholder: 'Please describe what has brought you here in your own words…',
        },
        {
          id: 'secondaryConcerns',
          label: 'Are there other concerns you would like to address?',
          type: 'textarea',
          minRows: 3,
          placeholder: 'List any additional concerns…',
        },
        {
          id: 'onsetDate',
          label: 'When did these concerns first begin?',
          type: 'select',
          options: ['Less than a week ago', '2–4 weeks ago', '1–3 months ago', '3–6 months ago', '6–12 months ago', '1–2 years ago', 'More than 2 years ago', 'As long as I can remember'],
        },
        {
          id: 'precipitatingEvent',
          label: 'Was there a specific event or life change that triggered or worsened these concerns?',
          type: 'textarea',
          minRows: 3,
          placeholder: 'e.g., divorce, job loss, death of a loved one, trauma…',
        },
        {
          id: 'severity',
          label: 'Rate the overall severity of your current concerns',
          type: 'scale',
          min: 1,
          max: 10,
          minLabel: 'Mild',
          maxLabel: 'Severe',
        },
        {
          id: 'dailyImpact',
          label: 'How are these concerns affecting your daily life (work, relationships, sleep, etc.)?',
          type: 'textarea',
          minRows: 3,
        },
        {
          id: 'priorAttempts',
          label: 'What have you already tried to address these concerns?',
          type: 'textarea',
          minRows: 2,
          placeholder: 'e.g., self-help books, prayer, exercise, medication, previous therapy…',
        },
        {
          id: 'whatHelps',
          label: 'What has been helpful, even partially?',
          type: 'textarea',
          minRows: 2,
        },
      ],
    },

    // ─── 4. Mental Health History ────────────────────────────────────────────
    {
      id: 'mentalHealth',
      title: 'Mental Health History',
      fields: [
        {
          id: 'previousTherapy',
          label: 'Have you received counseling or psychotherapy before?',
          type: 'radio',
          options: ['Yes', 'No'],
        },
        {
          id: 'therapyDetails',
          label: 'If yes, please describe (therapist name, dates, reason for ending)',
          type: 'textarea',
          minRows: 3,
          showIf: { field: 'previousTherapy', value: 'Yes' },
        },
        {
          id: 'psychiatricHospitalization',
          label: 'Have you ever been hospitalized for psychiatric reasons?',
          type: 'radio',
          options: ['Yes', 'No'],
        },
        {
          id: 'hospitalizationDetails',
          label: 'If yes, please describe (when, where, how long, reason)',
          type: 'textarea',
          minRows: 2,
          showIf: { field: 'psychiatricHospitalization', value: 'Yes' },
        },
        {
          id: 'diagnosedConditions',
          label: 'Have you ever received a mental health diagnosis?',
          type: 'radio',
          options: ['Yes', 'No', 'Unsure'],
        },
        {
          id: 'diagnosisDetails',
          label: 'Please list any diagnoses received',
          type: 'textarea',
          minRows: 2,
          placeholder: 'e.g., Major Depressive Disorder, GAD, PTSD, ADHD…',
          showIf: { field: 'diagnosedConditions', value: 'Yes' },
        },
        {
          id: 'suicidalHistory',
          label: 'Have you ever had thoughts of suicide or self-harm in the past (not currently)?',
          type: 'radio',
          options: ['Yes', 'No'],
        },
        {
          id: 'suicidalHistoryDetails',
          label: 'Please describe (when, context, what helped)',
          type: 'textarea',
          minRows: 2,
          showIf: { field: 'suicidalHistory', value: 'Yes' },
        },
        {
          id: 'attemptHistory',
          label: 'Have you ever made a suicide attempt?',
          type: 'radio',
          options: ['Yes', 'No'],
        },
        {
          id: 'attemptDetails',
          label: 'Please describe (approximate date, method, outcome)',
          type: 'textarea',
          minRows: 2,
          showIf: { field: 'attemptHistory', value: 'Yes' },
        },
      ],
    },

    // ─── 5. Medical History ──────────────────────────────────────────────────
    {
      id: 'medical',
      title: 'Medical History',
      fields: [
        {
          id: 'generalHealth',
          label: 'How would you rate your general physical health?',
          type: 'radio',
          options: ['Excellent', 'Good', 'Fair', 'Poor'],
        },
        {
          id: 'chronicConditions',
          label: 'Do you have any chronic medical conditions?',
          type: 'textarea',
          minRows: 2,
          placeholder: 'e.g., diabetes, thyroid disorder, chronic pain, heart disease…',
        },
        {
          id: 'recentIllness',
          label: 'Any recent significant illness, injury, or surgery?',
          type: 'textarea',
          minRows: 2,
        },
        {
          id: 'currentMedications',
          label: 'Please list all current medications (prescription and over-the-counter)',
          type: 'textarea',
          minRows: 3,
          placeholder: 'Name, dose, frequency, prescribing provider…',
        },
        {
          id: 'allergies',
          label: 'Known allergies (including medication allergies)',
          type: 'textarea',
          minRows: 2,
        },
        {
          id: 'pcpName',    label: 'Primary Care Physician', type: 'text', half: true },
        { id: 'pcpPractice', label: 'PCP Practice / Clinic', type: 'text', half: true },
        { id: 'pcpPhone',    label: 'PCP Phone',              type: 'tel',  half: true },
        { id: 'pcpFax',      label: 'PCP Fax',                type: 'tel',  half: true },
        {
          id: 'releaseToPhysician',
          label: 'May we communicate with your physician with a signed release?',
          type: 'radio',
          options: ['Yes', 'No', 'Undecided'],
        },
        {
          id: 'womenHealth',
          label: '(For those who may be pregnant) Are you currently pregnant or planning to become pregnant?',
          type: 'radio',
          options: ['Yes', 'No', 'Not applicable'],
        },
      ],
    },

    // ─── 6. Family History ───────────────────────────────────────────────────
    {
      id: 'family',
      title: 'Family History',
      fields: [
        {
          id: 'familyMentalHealth',
          label: 'Is there a family history of mental health conditions?',
          type: 'radio',
          options: ['Yes', 'No', 'Unknown'],
        },
        {
          id: 'familyMentalHealthDetails',
          label: 'Please describe (condition, family member relationship)',
          type: 'textarea',
          minRows: 3,
          placeholder: 'e.g., Mother – depression; Brother – bipolar disorder',
          showIf: { field: 'familyMentalHealth', value: 'Yes' },
        },
        {
          id: 'familySubstanceAbuse',
          label: 'Is there a family history of substance abuse or addiction?',
          type: 'radio',
          options: ['Yes', 'No', 'Unknown'],
        },
        {
          id: 'familySubstanceDetails',
          label: 'Please describe (substance, family member)',
          type: 'textarea',
          minRows: 2,
          showIf: { field: 'familySubstanceAbuse', value: 'Yes' },
        },
        {
          id: 'familyDomesticViolence',
          label: 'Was there domestic violence or abuse in your family of origin?',
          type: 'radio',
          options: ['Yes', 'No', 'Prefer not to say'],
        },
        {
          id: 'parentingStyle',
          label: 'How would you describe your childhood home environment?',
          type: 'select',
          options: ['Warm and supportive', 'Structured but caring', 'Strict / authoritarian', 'Neglectful', 'Chaotic / unstable', 'Abusive', 'Mixed', 'Other'],
        },
        {
          id: 'significantFamilyEvents',
          label: 'Any significant losses or traumatic events in your family',
          type: 'textarea',
          minRows: 3,
          placeholder: 'e.g., death of sibling, divorce of parents, unemployment, displacement…',
        },
        {
          id: 'relationshipWithParents',
          label: 'How would you describe your current relationship with your parents?',
          type: 'textarea',
          minRows: 2,
        },
      ],
    },

    // ─── 7. Developmental & Social History ──────────────────────────────────
    {
      id: 'social',
      title: 'Developmental & Social History',
      fields: [
        {
          id: 'educationLevel',
          label: 'Highest level of education completed',
          type: 'select',
          options: ['Some high school', 'High school diploma / GED', 'Some college', "Associate's degree", "Bachelor's degree", "Master's degree", 'Doctoral degree', 'Trade / vocational training'],
        },
        {
          id: 'employmentStatus',
          label: 'Current employment status',
          type: 'select',
          options: ['Full-time employed', 'Part-time employed', 'Self-employed', 'Unemployed', 'Retired', 'Student', 'Homemaker', 'Unable to work / disability'],
        },
        {
          id: 'jobSatisfaction',
          label: 'How satisfied are you with your work / school situation?',
          type: 'scale',
          min: 1,
          max: 10,
          minLabel: 'Very unsatisfied',
          maxLabel: 'Very satisfied',
        },
        {
          id: 'socialSupport',
          label: 'How would you describe your social support network?',
          type: 'textarea',
          minRows: 2,
          placeholder: 'Who do you lean on during difficult times?',
        },
        {
          id: 'hobbiesInterests',
          label: 'What are your hobbies, interests, or activities you enjoy?',
          type: 'textarea',
          minRows: 2,
        },
        {
          id: 'militaryService',
          label: 'Have you served in the military?',
          type: 'radio',
          options: ['Yes', 'No'],
        },
        {
          id: 'militaryDetails',
          label: 'Branch, years of service, combat exposure',
          type: 'textarea',
          minRows: 2,
          showIf: { field: 'militaryService', value: 'Yes' },
        },
        {
          id: 'legalHistory',
          label: 'Do you have any current or past legal issues?',
          type: 'radio',
          options: ['Yes', 'No'],
        },
        {
          id: 'legalDetails',
          label: 'Please describe',
          type: 'textarea',
          minRows: 2,
          showIf: { field: 'legalHistory', value: 'Yes' },
        },
      ],
    },

    // ─── 8. Relationship History ─────────────────────────────────────────────
    {
      id: 'relationships',
      title: 'Relationship History',
      fields: [
        {
          id: 'currentRelationshipSatisfaction',
          label: 'How satisfied are you with your current important relationships?',
          type: 'scale',
          min: 1,
          max: 10,
          minLabel: 'Very unsatisfied',
          maxLabel: 'Very satisfied',
        },
        {
          id: 'relationshipConflicts',
          label: 'Are there significant conflicts or difficulties in your current relationships?',
          type: 'textarea',
          minRows: 3,
          placeholder: 'Spouse, family members, coworkers, friends…',
        },
        {
          id: 'abuseInRelationships',
          label: 'Have you ever been in a physically, emotionally, or sexually abusive relationship?',
          type: 'radio',
          options: ['Yes', 'No', 'Prefer not to say'],
        },
        {
          id: 'abuseDetails',
          label: 'If you are comfortable sharing, please describe',
          type: 'textarea',
          minRows: 2,
          showIf: { field: 'abuseInRelationships', value: 'Yes' },
        },
        {
          id: 'sexualHistory',
          label: 'Are there sexual concerns or difficulties you would like to address in counseling?',
          type: 'radio',
          options: ['Yes', 'No', 'Prefer not to say'],
        },
        {
          id: 'sexualDetails',
          label: 'Please describe briefly',
          type: 'textarea',
          minRows: 2,
          showIf: { field: 'sexualHistory', value: 'Yes' },
        },
      ],
    },

    // ─── 9. Substance Use ────────────────────────────────────────────────────
    {
      id: 'substance',
      title: 'Substance Use',
      description: 'This information is confidential and helps us provide the most effective care.',
      fields: [
        {
          id: 'alcoholUse',
          label: 'Do you currently drink alcohol?',
          type: 'radio',
          options: ['Never', 'Occasionally (social / holiday)', 'Regularly', 'Daily', 'Previously but not currently'],
        },
        {
          id: 'alcoholAmount',
          label: 'On a typical drinking occasion, how many drinks do you have?',
          type: 'select',
          options: ['1–2', '3–4', '5–6', '7–9', '10 or more'],
          showIf: { field: 'alcoholUse', values: ['Occasionally (social / holiday)', 'Regularly', 'Daily'] },
        },
        {
          id: 'alcoholConcern',
          label: 'Has alcohol ever caused problems in your life or relationships?',
          type: 'radio',
          options: ['Yes', 'No'],
        },
        {
          id: 'tobaccoUse',
          label: 'Do you use tobacco or nicotine products?',
          type: 'radio',
          options: ['Never', 'Occasionally', 'Daily', 'Previously but not currently'],
        },
        {
          id: 'cannabisUse',
          label: 'Do you use cannabis / marijuana?',
          type: 'radio',
          options: ['Never', 'Occasionally', 'Regularly', 'Daily', 'Previously but not currently'],
        },
        {
          id: 'otherDrugs',
          label: 'Have you used any other recreational substances or misused prescription medications?',
          type: 'radio',
          options: ['Yes', 'No'],
        },
        {
          id: 'otherDrugsDetails',
          label: 'Please describe (substance, frequency, last use)',
          type: 'textarea',
          minRows: 2,
          showIf: { field: 'otherDrugs', value: 'Yes' },
        },
        {
          id: 'substanceTreatment',
          label: 'Have you ever received treatment for substance use?',
          type: 'radio',
          options: ['Yes', 'No'],
        },
        {
          id: 'substanceTreatmentDetails',
          label: 'Please describe (program, dates, outcome)',
          type: 'textarea',
          minRows: 2,
          showIf: { field: 'substanceTreatment', value: 'Yes' },
        },
      ],
    },

    // ─── 10. Trauma History ──────────────────────────────────────────────────
    {
      id: 'trauma',
      title: 'Trauma History',
      description:
        'We understand these topics may be sensitive. Please share only what you feel comfortable disclosing. This information helps us provide trauma-informed care.',
      fields: [
        {
          id: 'traumaExperiences',
          label: 'Have you experienced any of the following? (Select all that apply)',
          type: 'checkboxes',
          options: [
            'Physical abuse (childhood)',
            'Physical abuse (adult)',
            'Emotional / psychological abuse',
            'Sexual abuse or assault',
            'Neglect',
            'Domestic violence',
            'Serious accident or injury',
            'Natural disaster',
            'Combat / war exposure',
            'Witnessed violence',
            'Unexpected death of a loved one',
            'Life-threatening illness',
            'Community violence',
            'Other traumatic event',
          ],
        },
        {
          id: 'traumaDescription',
          label: 'If you would like to share more about any of the above, please do so here',
          type: 'textarea',
          minRows: 3,
        },
        {
          id: 'traumaImpact',
          label: 'How do you feel past trauma has affected you?',
          type: 'textarea',
          minRows: 3,
          placeholder: 'Emotionally, relationally, spiritually, physically…',
        },
        {
          id: 'traumaTherapy',
          label: 'Have you received trauma-focused therapy in the past?',
          type: 'radio',
          options: ['Yes', 'No'],
        },
        {
          id: 'traumaTherapyType',
          label: 'What type of therapy? (e.g., EMDR, CPT, somatic)',
          type: 'text',
          showIf: { field: 'traumaTherapy', value: 'Yes' },
        },
      ],
    },

    // ─── 11. Current Functioning ─────────────────────────────────────────────
    {
      id: 'functioning',
      title: 'Current Functioning',
      fields: [
        {
          id: 'sleepQuality',
          label: 'How is your sleep?',
          type: 'select',
          options: ['Good (7–9 hours, restful)', 'Fair (some difficulty)', 'Poor (difficulty falling or staying asleep)', 'Very poor (significant insomnia or excessive sleeping)'],
        },
        {
          id: 'appetite',
          label: 'How is your appetite?',
          type: 'select',
          options: ['Good / normal for me', 'Decreased', 'Increased', 'Very poor or compulsive'],
        },
        {
          id: 'energyLevel',
          label: 'Rate your typical daily energy level',
          type: 'scale',
          min: 1,
          max: 10,
          minLabel: 'Exhausted',
          maxLabel: 'High energy',
        },
        {
          id: 'concentration',
          label: 'How is your ability to concentrate?',
          type: 'select',
          options: ['Good / unaffected', 'Mild difficulty', 'Moderate difficulty', 'Severe difficulty'],
        },
        {
          id: 'exerciseFrequency',
          label: 'How often do you exercise?',
          type: 'select',
          options: ['Daily', '3–5 times per week', '1–2 times per week', 'Rarely', 'Never'],
        },
        {
          id: 'socialActivities',
          label: 'Are you participating in social activities?',
          type: 'select',
          options: ['Yes, as much as usual', 'Somewhat less than usual', 'Much less than usual', 'Isolated / not at all'],
        },
        {
          id: 'workPerformance',
          label: 'How is your work / school performance?',
          type: 'select',
          options: ['Not applicable', 'Good / as usual', 'Somewhat impaired', 'Significantly impaired', 'Unable to work / attend school'],
        },
        {
          id: 'overallMood',
          label: 'Rate your overall mood over the past two weeks',
          type: 'scale',
          min: 1,
          max: 10,
          minLabel: 'Very low',
          maxLabel: 'Very good',
        },
        {
          id: 'functionalConcerns',
          label: 'Are there other areas of daily functioning you would like to share?',
          type: 'textarea',
          minRows: 2,
        },
      ],
    },

    // ─── 12. Goals & Expectations ────────────────────────────────────────────
    {
      id: 'goals',
      title: 'Goals & Expectations',
      fields: [
        {
          id: 'counselingGoals',
          label: 'What are your specific goals for counseling?',
          type: 'textarea',
          required: true,
          minRows: 4,
          placeholder: 'Please be as specific as possible about what you hope to achieve…',
        },
        {
          id: 'successDefinition',
          label: 'What would success in counseling look like for you?',
          type: 'textarea',
          minRows: 3,
          placeholder: 'How will you know when you are ready to end counseling?',
        },
        {
          id: 'concerns',
          label: 'Do you have any concerns or reservations about counseling?',
          type: 'textarea',
          minRows: 2,
        },
        {
          id: 'counselorPreference',
          label: 'Do you have any preferences regarding your counselor?',
          type: 'textarea',
          minRows: 2,
          placeholder: 'e.g., gender, approach, faith background, cultural experience…',
        },
        {
          id: 'expectedDuration',
          label: 'How long do you expect to be in counseling?',
          type: 'select',
          options: ['A few sessions', '1–3 months', '3–6 months', '6–12 months', 'Long-term (more than a year)', 'Not sure'],
        },
      ],
    },

    // ─── 13. Faith & Spiritual Profile ──────────────────────────────────────
    {
      id: 'faith',
      title: 'Faith & Spiritual Profile',
      description:
        'As a Christian counseling practice, faith integration is central to our approach. We respect all backgrounds and integrate faith at the level you desire. Please share as much as you are comfortable with.',
      fields: [
        {
          id: 'faithBackground',
          label: 'Describe your religious or spiritual background',
          type: 'textarea',
          minRows: 2,
          placeholder: 'e.g., raised Baptist, recently became a Christian, exploring faith, no religious background…',
        },
        {
          id: 'denomination',
          label: 'Denomination or faith tradition (if applicable)',
          type: 'select',
          options: ['Evangelical', 'Baptist', 'Catholic', 'Methodist', 'Presbyterian', 'Pentecostal / Charismatic', 'Non-denominational', 'Lutheran', 'Anglican / Episcopal', 'Reformed / Calvinist', 'Orthodox Christian', 'Jewish', 'Muslim', 'Hindu', 'Buddhist', 'Other', 'None'],
        },
        {
          id: 'churchAttendance',
          label: 'How often do you attend church or worship services?',
          type: 'select',
          options: ['More than once a week', 'Weekly', '2–3 times a month', 'Monthly', 'A few times a year', 'Rarely', 'Not currently / Never'],
        },
        {
          id: 'churchName',
          label: 'Name of your church or faith community',
          type: 'text',
          half: true,
        },
        {
          id: 'pastorName',
          label: 'Pastor / Priest / Spiritual leader name',
          type: 'text',
          half: true,
        },
        {
          id: 'hasSpiritualDirector',
          label: 'Do you have a spiritual director or mentor?',
          type: 'radio',
          options: ['Yes', 'No'],
        },
        {
          id: 'spiritualDirectorName',
          label: 'Name of your spiritual director / mentor',
          type: 'text',
          showIf: { field: 'hasSpiritualDirector', value: 'Yes' },
        },
        {
          id: 'faithImportance',
          label: 'How central is your faith to your identity and daily life?',
          type: 'scale',
          min: 1,
          max: 10,
          minLabel: 'Not important',
          maxLabel: 'Absolutely central',
        },
        {
          id: 'prayerLife',
          label: 'How would you describe your prayer life?',
          type: 'select',
          options: ['Daily, consistent', 'Several times a week', 'Occasionally', 'Rarely', 'Not currently', 'Not applicable'],
        },
        {
          id: 'bibleReading',
          label: 'How often do you read or study the Bible?',
          type: 'select',
          options: ['Daily', 'Several times a week', 'Occasionally', 'Rarely', 'Not currently', 'Not applicable'],
        },
        {
          id: 'spiritualDisciplines',
          label: 'Which spiritual practices are part of your regular life?',
          type: 'checkboxes',
          options: ['Prayer', 'Bible reading / study', 'Worship / praise', 'Fasting', 'Small group / Bible study', 'Journaling', 'Service / volunteering', 'Meditation on Scripture', 'Accountability partner', 'Sabbath rest'],
        },
        {
          id: 'faithAndPresentingConcern',
          label: 'How is your faith related to the concerns that bring you to counseling?',
          type: 'textarea',
          minRows: 3,
          placeholder: 'Is your faith a source of strength? A source of additional struggle? Both?',
        },
        {
          id: 'spiritualStruggle',
          label: 'Are you experiencing any spiritual struggles, doubts, or crises?',
          type: 'radio',
          options: ['Yes', 'No', 'Somewhat'],
        },
        {
          id: 'spiritualStruggleDetails',
          label: 'Please describe your spiritual struggles or doubts',
          type: 'textarea',
          minRows: 3,
          showIf: { field: 'spiritualStruggle', value: 'Yes' },
        },
        {
          id: 'spiritualStrengths',
          label: 'What spiritual strengths, resources, or scriptures are sources of comfort and hope for you?',
          type: 'textarea',
          minRows: 3,
          placeholder: 'e.g., "I can do all things through Christ" (Phil 4:13), the Lord\'s Prayer, community support…',
        },
        {
          id: 'openToFaithIntegration',
          label: 'How would you like faith integrated into your counseling?',
          type: 'select',
          options: [
            'Essential — faith must be central to all sessions',
            'Strongly preferred — please actively incorporate Scripture and prayer',
            'Welcome — incorporate faith when relevant',
            'Open — OK to mention faith, not a primary focus',
            'Prefer secular — please minimize faith content',
          ],
        },
        {
          id: 'openToPrayerInSession',
          label: 'Are you open to praying together during sessions?',
          type: 'radio',
          options: ['Yes, I would welcome this', 'Yes, occasionally', 'Not at this time', 'No'],
        },
        {
          id: 'christianGoals',
          label: 'Are there specific faith-based goals you hope to work on?',
          type: 'textarea',
          minRows: 3,
          placeholder: 'e.g., deepen trust in God, forgiveness, overcoming shame, growing in prayer, aligning values…',
        },
        {
          id: 'faithAffectingHealing',
          label: 'Do you believe God can bring healing and restoration in your situation?',
          type: 'radio',
          options: ['Yes, strongly', 'I hope so', 'I\'m uncertain', 'I struggle to believe this right now'],
        },
        {
          id: 'faithCommunitySupport',
          label: 'Does your faith community know you are seeking counseling, and are they supportive?',
          type: 'radio',
          options: ['Yes, they are supportive', 'They know but aren\'t very involved', 'They don\'t know', 'I don\'t have a faith community currently'],
        },
      ],
    },

    // ─── 14. Safety Assessment ────────────────────────────────────────────────
    {
      id: 'safety',
      title: 'Safety Assessment',
      description:
        'Your safety is our highest priority. Please answer these questions honestly. If you are in immediate danger, please call 911 or the 988 Suicide & Crisis Lifeline (call or text 988).',
      color: 'red',
      fields: [
        {
          id: 'currentSelfHarmThoughts',
          label: 'Are you currently having thoughts of hurting or harming yourself?',
          type: 'radio',
          options: ['Yes', 'No'],
          required: true,
        },
        {
          id: 'currentSuicidalIdeation',
          label: 'Are you currently having thoughts of suicide or ending your life?',
          type: 'radio',
          options: ['Yes', 'No'],
          required: true,
        },
        {
          id: 'suicidalPlan',
          label: 'If yes, do you have a plan?',
          type: 'radio',
          options: ['Yes', 'No'],
          showIf: { field: 'currentSuicidalIdeation', value: 'Yes' },
        },
        {
          id: 'suicidalIntent',
          label: 'If yes, do you intend to act on these thoughts?',
          type: 'radio',
          options: ['Yes', 'No', 'Unsure'],
          showIf: { field: 'currentSuicidalIdeation', value: 'Yes' },
        },
        {
          id: 'harmingOthers',
          label: 'Are you having any thoughts of harming others?',
          type: 'radio',
          options: ['Yes', 'No'],
          required: true,
        },
        {
          id: 'safetyDetails',
          label: 'Please describe any safety concerns you answered Yes to above',
          type: 'textarea',
          minRows: 3,
        },
        {
          id: 'protectiveFactors',
          label: 'What are your reasons for living? What keeps you going?',
          type: 'textarea',
          minRows: 3,
          placeholder: 'Family, faith, goals, people who depend on you…',
        },
        {
          id: 'crisisContact',
          label: 'Who would you call if you were in a crisis?',
          type: 'text',
          placeholder: 'Name and relationship',
        },
        {
          id: 'crisisPhone',
          label: 'Their phone number',
          type: 'tel',
        },
        {
          id: 'safetyPlanAware',
          label: 'Do you have a current safety plan?',
          type: 'radio',
          options: ['Yes', 'No', 'Not sure what this is'],
        },
      ],
    },
  ],
};
