// Short Intake Form — ~10 minutes, essential pre-session information
export const ShortIntakeForm = {
  id: 'short_intake',
  title: 'Short Intake Form',
  description:
    'A brief, concise intake questionnaire to gather essential information before your first counseling session.',
  icon: '📋',
  color: 'brand',
  estimatedMinutes: 10,
  sections: [
    {
      id: 'personal',
      title: 'Personal Information',
      fields: [
        { id: 'firstName',    label: 'First Name',         type: 'text',   required: true,  half: true },
        { id: 'lastName',     label: 'Last Name',          type: 'text',   required: true,  half: true },
        { id: 'dob',          label: 'Date of Birth',      type: 'date',   required: true,  half: true },
        { id: 'gender',       label: 'Gender Identity',    type: 'select', half: true,
          options: ['Male', 'Female', 'Non-binary / Non-conforming', 'Prefer not to say', 'Other'] },
        { id: 'phone',        label: 'Phone Number',       type: 'tel',    required: true,  half: true },
        { id: 'email',        label: 'Email Address',      type: 'email',  required: true,  half: true },
        { id: 'maritalStatus', label: 'Marital Status',   type: 'select', half: true,
          options: ['Single', 'Married', 'Separated', 'Divorced', 'Widowed', 'Partnered / Engaged'] },
        { id: 'referredBy',   label: 'How did you hear about us?', type: 'text', half: true },
      ],
    },
    {
      id: 'presenting',
      title: 'Presenting Concerns',
      fields: [
        {
          id: 'concern',
          label: 'Briefly describe your main reason for seeking counseling',
          type: 'textarea',
          required: true,
          minRows: 4,
          placeholder: 'Please share what has brought you here today…',
        },
        {
          id: 'duration',
          label: 'How long have you been experiencing this?',
          type: 'select',
          options: ['Less than a week', '1–4 weeks', '1–3 months', '3–6 months', '6–12 months', 'More than a year'],
        },
        {
          id: 'severity',
          label: 'How much is this affecting your daily life?',
          type: 'scale',
          min: 1,
          max: 10,
          minLabel: 'Barely at all',
          maxLabel: 'Completely',
        },
        {
          id: 'previousCounseling',
          label: 'Have you received counseling before?',
          type: 'radio',
          options: ['Yes', 'No'],
        },
        {
          id: 'previousCounselingDetails',
          label: 'If yes, briefly describe your previous counseling experience',
          type: 'textarea',
          minRows: 2,
          showIf: { field: 'previousCounseling', value: 'Yes' },
        },
      ],
    },
    {
      id: 'medical',
      title: 'Medical & Mental Health',
      fields: [
        {
          id: 'currentMedications',
          label: 'Are you currently taking any medications?',
          type: 'radio',
          options: ['Yes', 'No'],
        },
        {
          id: 'medicationList',
          label: 'Please list your medications and dosages',
          type: 'textarea',
          minRows: 2,
          placeholder: 'e.g., Sertraline 50 mg daily…',
          showIf: { field: 'currentMedications', value: 'Yes' },
        },
        {
          id: 'mentalHealthDiagnosis',
          label: 'Have you ever been diagnosed with a mental health condition?',
          type: 'radio',
          options: ['Yes', 'No'],
        },
        {
          id: 'diagnosisList',
          label: 'Please list any diagnoses',
          type: 'textarea',
          minRows: 2,
          placeholder: 'e.g., Generalized Anxiety Disorder, Depression…',
          showIf: { field: 'mentalHealthDiagnosis', value: 'Yes' },
        },
        {
          id: 'pcpName',
          label: 'Primary Care Physician name (optional)',
          type: 'text',
          half: true,
        },
        {
          id: 'pcpPhone',
          label: 'PCP Phone (optional)',
          type: 'tel',
          half: true,
        },
      ],
    },
    {
      id: 'goals',
      title: 'Goals for Counseling',
      fields: [
        {
          id: 'goals',
          label: 'What are your goals for counseling?',
          type: 'textarea',
          required: true,
          minRows: 3,
          placeholder: 'What would you like to accomplish or change?',
        },
        {
          id: 'successLooks',
          label: 'What would success look like for you?',
          type: 'textarea',
          minRows: 2,
          placeholder: 'How will you know counseling has helped?',
        },
      ],
    },
    {
      id: 'faith',
      title: 'Faith & Spiritual Profile',
      description:
        'As a Christian counseling practice, we integrate faith principles when appropriate and desired. Please share as much or as little as you\'re comfortable with. All information is confidential.',
      fields: [
        {
          id: 'faithBackground',
          label: 'What is your religious or faith background?',
          type: 'text',
          placeholder: 'e.g., Evangelical Christian, Catholic, Baptist, None…',
        },
        {
          id: 'churchAffiliation',
          label: 'Do you attend a church or faith community?',
          type: 'radio',
          options: ['Yes, regularly', 'Yes, occasionally', 'No'],
        },
        {
          id: 'churchName',
          label: 'Name of church or faith community',
          type: 'text',
          showIf: { field: 'churchAffiliation', value: 'Yes, regularly' },
        },
        {
          id: 'faithImportance',
          label: 'How important is your faith to your daily life?',
          type: 'scale',
          min: 1,
          max: 10,
          minLabel: 'Not important',
          maxLabel: 'Extremely important',
        },
        {
          id: 'faithAndConcern',
          label: 'Do you feel your current struggles are affecting your relationship with God?',
          type: 'radio',
          options: ['Yes', 'No', 'Unsure'],
        },
        {
          id: 'christianIntegration',
          label: 'Would you like Christian counseling principles integrated into your sessions?',
          type: 'radio',
          options: ['Yes, please', 'No, prefer secular approach', 'Open to it'],
        },
        {
          id: 'spiritualStrengths',
          label: 'What spiritual practices or scriptures bring you comfort or strength?',
          type: 'textarea',
          minRows: 2,
          placeholder: 'e.g., Prayer, Psalm 23, church community, worship music…',
        },
        {
          id: 'hasPastor',
          label: 'Do you have a pastor or spiritual mentor?',
          type: 'radio',
          options: ['Yes', 'No'],
        },
        {
          id: 'pastorName',
          label: 'Pastor / Spiritual mentor name (optional)',
          type: 'text',
          showIf: { field: 'hasPastor', value: 'Yes' },
        },
      ],
    },
    {
      id: 'safety',
      title: 'Safety Screening',
      description:
        'Your safety is our highest priority. Please answer these questions honestly so we can provide the best care. If you are in immediate danger, please call 911 or the 988 Suicide & Crisis Lifeline.',
      color: 'red',
      fields: [
        {
          id: 'selfHarmThoughts',
          label: 'Are you currently having thoughts of harming yourself?',
          type: 'radio',
          options: ['Yes', 'No'],
          required: true,
        },
        {
          id: 'suicidalThoughts',
          label: 'Are you currently having thoughts of suicide?',
          type: 'radio',
          options: ['Yes', 'No'],
          required: true,
        },
        {
          id: 'harmingOthers',
          label: 'Are you having thoughts of harming others?',
          type: 'radio',
          options: ['Yes', 'No'],
          required: true,
        },
        {
          id: 'safetyNote',
          label: 'If you answered Yes to any of the above, please describe briefly',
          type: 'textarea',
          minRows: 2,
        },
      ],
    },
  ],
};
